/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ImageC */

#ifndef _Included_ImageC
#define _Included_ImageC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ImageC
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ImageC_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ImageC
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ImageC_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     ImageC
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ImageC_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     ImageC
 * Method:    getRed
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ImageC_getRed
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ImageC
 * Method:    getGreen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ImageC_getGreen
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ImageC
 * Method:    getBlue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ImageC_getBlue
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ImageC
 * Method:    setRed
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ImageC_setRed
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ImageC
 * Method:    setGreen
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ImageC_setGreen
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ImageC
 * Method:    setBlue
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ImageC_setBlue
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ImageC
 * Method:    applyBlurFilter
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ImageC_applyBlurFilter
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
