/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    allocateMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_allocateMemory
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    getStringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Main_getStringLength
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Main
 * Method:    createObject
 * Signature: ()LMain;
 */
JNIEXPORT jobject JNICALL Java_Main_createObject
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    setObjectField
 * Signature: (LMain;I)V
 */
JNIEXPORT void JNICALL Java_Main_setObjectField
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     Main
 * Method:    allocateStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Main_allocateStruct
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    getStructValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Main_getStructValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Main
 * Method:    freeStruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Main_freeStruct
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Main
 * Method:    divideByZero
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_divideByZero
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
